# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

project_name: kpdbug

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/kpdbug/main.go
    binary: kpdbug
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    # this name template makes the tarballs look like
    # kpdbug_1.0.0_Darwin_x86_64.tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# The lines below are responsible for generating the Homebrew formula
brews:
  -
    # Name template of the recipe
    # Default to project name
    name: kpdbug

    # Repository to push the tap to.
    repository:
      owner: felipe-veas
      name: homebrew-tap
      # token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}" # optional, defaults to GITHUB_TOKEN

    # Valid: "github" (default), "gitlab" or "gitea"
    # url_template: "https://github.com/myuser/myrepo/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    directory: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/felipe-veas/k8s-pods-debug"

    # Template of your app's description.
    # Default is empty.
    description: "Kubernetes pod debugging tool"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be published to the homebrew tap if
    # there is an error creating or updating the formula.
    # Default is false.
    skip_upload: auto

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/kpdbug --version"
